name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"

      - name: Install dependencies
        run: npm ci
        working-directory: Frontend

      - name: Build the application
        run: npm run build
        working-directory: Frontend

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: Frontend
          start: npm start
          wait-on: "http://localhost:3000"
          config-file: "cypress.config.js"
