name: Dashboard Online Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"

      - name: Install dependencies
        run: npm ci
        working-directory: Frontend

      - name: See if dashboard works
        run: npm run build
        working-directory: Frontend
